// One entry per paper. `year` is only used for grouping/sorting — papers
// are bucketed by it into year containers, newest year first; within a
// year, cards render in the order they appear in this array.
//
// `image` still points at the shared placeholder figure for every entry —
// swap in each paper's real figure filename once those assets exist.
// `doiUrl` values were looked up from Crossref (matched by title/author/
// journal/year) rather than typed in by hand — a few (e.g. the very
// newest 2025/2026 entries, and some pre-2010 ones) use non-numeric or
// unusual-looking DOI suffixes because that's what the publisher actually
// registered; that's not a transcription error.
const PUBLICATIONS = [
  {
    year: 2026,
    image: "Publication/Spectrally Encoded Proximity-Field Nanopatterning.png",
    title: "Spectrally Encoded Proximity-Field Nanopatterning",
    authors: "Junhyung Park*, Yun Hyeong*, Hwanseok Chang, Dohyun Kim, Junkyo Jung, Seokwoo Jeon, Jonghwa Shin‡",
    journal: "Advanced Optical Materials, e03274 (2026)",
    doiUrl: "https://doi.org/10.1002/adom.202503274",
  },
  {
    year: 2026,
    image: "Publication/Arbitrary Total Angular Momentum Vectorial Holography Using Bi-Layer Metasurfaces.png",
    title: "Arbitrary Total Angular Momentum Vectorial Holography Using Bi-Layer Metasurfaces",
    authors: "Joonkyo Jung*, Hyeonhee Kim, Jonghwa Shin‡",
    journal: "Advanced Materials 38, 15, e19106 (2026)",
    doiUrl: "https://doi.org/10.1002/adma.202519106",
  },
  {
    year: 2026,
    image: "",
    // Left as initials (not spelled out) until the real full names are
    // confirmed — doiUrl too. Mingwan Cho gets both marks per instruction
    // (co-first + corresponding); the rest are exactly as given.
    title: "Angle-and polarization-adaptive aperiodic-anisotropic metasurfaces for broadband reflectance suppression",
    authors: "J Yoon, M Cho*‡, H Kim, H Park, IS Joe, J Shin",
    journal: "iScience 29, 8 (2026)",
    doiUrl: "",
  },
  {
    year: 2026,
    image: "",
    title: "Analogs of Spontaneous Emission and Lasing in Photonic Time Crystals",
    authors: "Kyungmin Lee, Minwook Kyung, Yung Kim, Jagang Park, Hansuek Lee, Joonhee Choi, C. T. Chan, Jonghwa Shin, Kun Woo Kim, Bumki Min",
    journal: "Physical Review Letters 136, 9, 093802 (2026)",
    doiUrl: "https://doi.org/10.1103/hh9h-qzpk",
  },
  {
    year: 2026,
    image: "",
    title: "Electronic Trap Detection with Carrier-Resolved Photo-Hall Effect",
    authors: "Oki Gunawan, Chaeyoun Kim, Bonfilio Nainggolan, Minyeul Lee, Jonghwa Shin, Dong Suk Kim, Yimhyun Jo, Minjin Kim, Julie Euvrard, Douglas Bishop, Frank Libsch, Teodor Todorov, Yunna Kim, Byungha Shin",
    journal: "Science Advances 12, 1, eadz0460 (2026)",
    doiUrl: "https://doi.org/10.1126/sciadv.adz0460",
  },
  {
    year: 2026,
    image: "",
    title: "Eschallot: A Topology Nucleation Algorithm for Designing Stratified, Spherically Symmetric Systems That Exhibit Complex Angular Scattering of Electromagnetic Waves",
    authors: "Seokhwan Min, Jonghwa Shin",
    journal: "Computer Physics Communications 320, 109966 (2026)",
    doiUrl: "https://doi.org/10.1016/j.cpc.2025.109966",
  },
  {
    year: 2025,
    image: "Publication/Dynamic realization of emergent high-dimensional optical vortices.webp",
    title: "Dynamic realization of emergent high-dimensional optical vortices",
    authors: "Dongha Kim*, Geonhyeong Park*, Yun-Seok Choi, Arthur Baucour, Jisung Hwang, Jaeyu Kim, Sanghyeok Park, Hee Seong Yun, Jonghwa Shin, Haiwen Wang, Shanhui Fan, Dong Ki Yoon‡, Min-Kyo Seo‡",
    journal: "Nature Communications 16, 788 (2025)",
    doiUrl: "https://doi.org/10.1038/s41467-025-65087-2",
  },
  {
    year: 2025,
    image: "Publication/Spontaneous Emission Decay and Excitation in Photonic Time Crystals.png",
    title: "Spontaneous Emission Decay and Excitation in Photonic Time Crystals",
    authors: "Jagang Park*, Kyungmin Lee*, Ruo-Yang Zhang, Hee-Chul Park, Jung-Wan Ryu, Gil Young Cho, Min Yeul Lee, Zhaoqing Zhang, Namkoo Park, Wonju Jeon, Jonghwa Shin, C. T. Chan, Bumki Min‡",
    journal: "Physical Review Letters 135, 13, 133801 (2025)",
    doiUrl: "https://doi.org/10.1103/5v2w-yg7v",
  },
  {
    year: 2025,
    image: "Publication/Angle- and Polarization-Tolerant Metasurface Designs Based on the Aperiodic Tiling.png",
    title: "Angle- and Polarization-Tolerant Metasurface Designs Based on the Aperiodic Tiling",
    authors: "Minyeul Lee*, Suwan Jeon, Jonghwa Shin‡",
    journal: "Advanced Optical Materials 13, 20, 2500455 (2025)",
    doiUrl: "https://doi.org/10.1002/adom.202500455",
  },
  {
    year: 2025,
    image: "Publication/Nanophotonic device design based on large language models multilayer and metasurface examples.png",
    title: "Nanophotonic device design based on large language models: multilayer and metasurface examples",
    authors: "Myungjoon Kim*, Hyeonjin Park*, Jonghwa Shin‡",
    journal: "Nanophotonics 14, 8, 1273-1282 (2025)",
    doiUrl: "https://doi.org/10.1515/nanoph-2024-0674",
  },
  {
    year: 2025,
    image: "Publication/Fast Free-Form Phase Mask Design for Three-Dimensional Photolithography Using Convergent Born Series.gif",
    title: "Fast Free-Form Phase Mask Design for Three-Dimensional Photolithography Using Convergent Born Series",
    authors: "Dohyeon Lee*, Moosung Lee, Bakytgul Yerenzhep, Myungjoon Kim, Herve Hugonnet, Seokwoo Jeon, Jonghwa Shin, YongKeun Park‡",
    journal: "ACS Photonics 12, 2, 610-619 (2025)",
    doiUrl: "https://doi.org/10.1021/acsphotonics.4c01201",
  },
  {
    year: 2025,
    image: "Publication/Inverse design of nanophotonic devices enabled by optimization algorithms and deep learning recent achievements and future prospects.png",
    title: "Inverse design of nanophotonic devices enabled by optimization algorithms and deep learning: recent achievements and future prospects",
    authors: "Junhyeong Kim*, Jae-Yong Kim*, Jungmin Kim, Yun Hyeong, Berkay Neseli, Jong-Bum You, Joonsup Shim, Jonghwa Shin, Hyo-Hoom Park, Hamza Kurt‡",
    journal: "Nanophotonics 14, 2, 121-151 (2025)",
    doiUrl: "https://doi.org/10.1515/nanoph-2024-0536",
  },
  {
    year: 2025,
    image: "",
    title: "Manufacturing of a Bitmap-Type Lightweight Microwave Absorber Metasurface",
    authors: "Je-Ryung Lee, Myungjoon Kim, Seung Hwan Moon, Doo-Sun Choi, Jonghwa Shin, Ik Soo Kang, Tae-Jin Je, Eun-chae Jeon",
    journal: "International Journal of Precision Engineering and Manufacturing 26, 3461-3472 (2025)",
    doiUrl: "https://doi.org/10.1007/s12541-025-01326-2",
  },
  {
    year: 2024,
    image: "Publication/Highly Tunable, Nanomaterial-Functionalized Structural Templating of Intracellular Protein Structures Within Biological Species.png",
    title: "Highly Tunable, Nanomaterial-Functionalized Structural Templating of Intracellular Protein Structures Within Biological Species",
    authors: "Dae-Hyeon Song*, Chang Woo Song*, Seunghee H. Cho*, Tae Yoon Kwon, Hoeyun Jung, Ki Hyun Park, Jiyun Kim, Junyoung Seo, Jaeyoung Yoo, Minjoon Kim, Gyu Rac Lee, Jisung Hwang, Hyuck Mo Lee, Jonghwa Shin, Jennifer H. Shin, Yeon Sik Jung‡, Jae-Byum Chang‡",
    journal: "Advanced Science 2406492 (2024)",
    doiUrl: "https://doi.org/10.1002/advs.202406492",
  },
  {
    year: 2024,
    image: "Publication/Realizing Square-Ordered Nanopillars with a 0.1-Tera-Density through a Superimposed Masking Strategy for Advanced Surface-Enhanced Raman Spectroscopy.gif",
    title: "Realizing Square-Ordered Nanopillars with a 0.1-Tera-Density through a Superimposed Masking Strategy for Advanced Surface-Enhanced Raman Spectroscopy",
    authors: "Seungkyun Lee*, Minjae Ku*, Heejin Lim*, Jisung Hwang, Jong Min Kim, Hanhwi Kim, Jonghwa Shin, Hyeuk Jin Han‡, Yeon Sik Jung‡",
    journal: "ACS Applied Materials & Interfaces 16, 50, 69703-69712 (2024)",
    doiUrl: "https://doi.org/10.1021/acsami.4c15062",
  },
  {
    year: 2024,
    image: "Publication/In silico full-angle high-dynamic range scattering of microscopic objects exploiting holotomography.jpg",
    title: "In silico full-angle high-dynamic range scattering of microscopic objects exploiting holotomography",
    authors: "Seung Kyu Kang*, Kyoohyun Kim, Jinsoo Jeong, Sunghee Hong, YongKeun Park‡, Jonghwa Shin‡",
    journal: "Biomedical Optics Express 15, 9, 5238-5250 (2024)",
    doiUrl: "https://doi.org/10.1364/boe.528698",
  },
  {
    year: 2024,
    image: "Publication/Tree-Inspired Aerogel Comprising Nonoxidized Graphene Flakes and Cellulose as Solar Absorber for Efficient Water Generation.gif",
    title: "Tree-Inspired Aerogel Comprising Nonoxidized Graphene Flakes and Cellulose as Solar Absorber for Efficient Water Generation",
    authors: "Qiang Chen*, Minwoo Choi, Haomin Chen, Jin Kim, Caiyan Qin, Youngjin Ham, Myungwoo Choi, Haibo Zeng, Jonghwa Shin, Bong Jae Lee‡, Seokwoo Jeon‡",
    journal: "Nano Letters 24, 34, 10583-10591 (2024)",
    doiUrl: "https://doi.org/10.1021/acs.nanolett.4c02742",
  },
  {
    year: 2024,
    image: "Publication/Bidirectional Vectorial Holography Using Bi-Layer Metasurfaces and Its Application to Optical Encryption.png",
    title: "Bidirectional Vectorial Holography Using Bi-Layer Metasurfaces and Its Application to Optical Encryption",
    authors: "Hyeonhee Kim*, Joonkyo Jung*, Jonghwa Shin‡",
    journal: "Advanced Materials 36, 44, 2406717 (2024)",
    doiUrl: "https://doi.org/10.1002/adma.202406717",
  },
  {
    year: 2024,
    image: "Publication/Compression-Sensitive Smart Windows Inclined Pores for Dynamic Transparency Changes.webp",
    title: "Compression-Sensitive Smart Windows: Inclined Pores for Dynamic Transparency Changes",
    authors: "Haomin Chen*, Gunho Chang, Tae Hee Lee, Seokhwan Min, Sanghyeon Nam, Donghwi Cho, Kwonhwan Ko, Gwangmin Bae, Yoonseong Lee, Jirou Feng, Heng Zhang, Jang-Kyo Kim, Jonghwa Shin, Jung-Wuk Hong‡, Seokwoo Jeon‡",
    journal: "Nature Communications 15, 8074 (2024)",
    doiUrl: "https://doi.org/10.1038/s41467-024-52305-6",
  },
  {
    year: 2024,
    image: "Publication/Tunable metamaterials with carrier-induced effective permittivity for active control of electromagnetic fields in semiconductor manufacturing device.jpg",
    title: "Tunable metamaterials with carrier-induced effective permittivity for active control of electromagnetic fields in semiconductor manufacturing device",
    authors: "Minyeul Lee*, Sungyoung Yoon*, Meehyun Lim, Sungyeol Kim, Jonghwa Shin‡",
    journal: "Plasma Sources Science and Technology 33, 6, 065013 (2024)",
    doiUrl: "https://doi.org/10.1088/1361-6595/ad57ee",
  },
  {
    year: 2024,
    image: "Publication/Realization of all two-dimensional Bravais lattices with metasurface-based interference lithography.png",
    title: "Realization of all two-dimensional Bravais lattices with metasurface-based interference lithography",
    authors: "Myungjoon Kim*, Nayoung Kim*, Jonghwa Shin‡",
    journal: "Nanophotonics 13, 8, 1467-1474 (2024)",
    doiUrl: "https://doi.org/10.1515/nanoph-2023-0786",
  },
  {
    year: 2024,
    image: "Publication/Color arrestor pixels for high-fidelity, high-sensitivity imaging sensors.jpg",
    title: "Color arrestor pixels for high-fidelity, high-sensitivity imaging sensors",
    authors: "Mingwan Cho*, Joonkyo Jung, Myungjoon Kim, Jeong Yub Lee, Seokhwan Min, Jongwoo Hong, Shinho Lee, Minsung Heo, Jong Uk Kim, In-Sung Joe‡, Jonghwa Shin‡",
    journal: "Nanophotonics 13, 16, 2971-2982 (2024)",
    doiUrl: "https://doi.org/10.1515/nanoph-2024-0064",
  },
  {
    year: 2023,
    image: "Publication/Visual and thermal camouflage on different terrestrial environments based on electrochromism.png",
    title: "Visual and thermal camouflage on different terrestrial environments based on electrochromism",
    authors: "Suwan Jeon*, Su Eon Lee*, Wonjoong Kim*, Seokhwan Min, Seung Won Seon, Seung Ho Han, Bong Hoon Kim‡, Heon Lee‡, Jonghwa Shin‡",
    journal: "Nanophotonics 12, 15, 3199-3209 (2023)",
    doiUrl: "https://doi.org/10.1515/nanoph-2023-0244",
  },
  {
    year: 2023,
    image: "Publication/Customizing Radiative Decay Dynamics of Two-Dimensional Excitons via Position- and Polarization-Dependent Vacuum-Field Interference.gif",
    title: "Customizing Radiative Decay Dynamics of Two-Dimensional Excitons via Position- and Polarization-Dependent Vacuum-Field Interference",
    authors: "Sanghyeok Park*, Dongha Kim*, Yun-Seok Choi, Arthur Baucour, Donghyeong Kim, Sangho Yoon, Kenji Watanabe, Takashi Taniguchi, Jonghwa Shin, Jonghwan Kim, Min-Kyo Seo‡",
    journal: "Nano Letters 23, 6, 2158-2165 (2023)",
    doiUrl: "https://doi.org/10.1021/acs.nanolett.2c04604",
  },
  {
    year: 2023,
    image: "Publication/Highly angle-sensitive and efficient optical metasurfaces with broken mirror symmetry.png",
    title: "Highly angle-sensitive and efficient optical metasurfaces with broken mirror symmetry",
    authors: "Nayoung Kim*, Myungjoon Kim, Joonkyo Jung, Taeyong Chang, Suwan Jeon, Jonghwa Shin‡",
    journal: "Nanophotonics 12, 13, 2347-2358 (2023)",
    doiUrl: "https://doi.org/10.1515/nanoph-2022-0793",
  },
  {
    year: 2023,
    image: "Publication/Three-dimensionally reconfigurable focusing of laser by mechanically tunable metalens doublet with built-in holograms for alignment.png",
    title: "Three-dimensionally reconfigurable focusing of laser by mechanically tunable metalens doublet with built-in holograms for alignment",
    authors: "Joonkyo Jung*, Hyeonhee Kim*, Jonghwa Shin‡",
    journal: "Nanophotonics 12, 8 (2023)",
    doiUrl: "https://doi.org/10.1515/nanoph-2022-0634",
  },
  {
    year: 2023,
    image: "Publication/Daylong sub-ambient radiative cooling with full-color exterior based on thermal radiation and solar decoupling.png",
    title: "Daylong sub-ambient radiative cooling with full-color exterior based on thermal radiation and solar decoupling",
    authors: "Suwan Jeon*, Soomin Son, Seokhwan Min, Hyeonjin Park, Heon Lee‡, Jonghwa Shin‡",
    journal: "Advanced Optical Materials 11, 2202129 (2023)",
    doiUrl: "https://doi.org/10.1002/adom.202202129",
  },
  {
    year: 2022,
    image: "Publication/Spontaneous generation and active manipulation of real-space optical vortices.webp",
    title: "Spontaneous generation and active manipulation of real-space optical vortices",
    authors: "Dongha Kim*, Arthur Baucour, Yun-Seok Choi, Jonghwa Shin, Min-Kyo Seo‡",
    journal: "Nature 611, 48-54 (2022)",
    doiUrl: "https://doi.org/10.1038/s41586-022-05229-4",
  },
  {
    year: 2022,
    image: "Publication/Universal metasurfaces for complete linear control of coherent light transmission.png",
    title: "Universal metasurfaces for complete linear control of coherent light transmission",
    authors: "Taeyong Chang*, Joonkyo Jung*, Sang-Hyeon Nam, Hyeonhee Kim, Jong Uk Kim, Nayoung Kim, Suwan Jeon, Minseong Heo, Jonghwa Shin‡",
    journal: "Advanced Materials 34, 2204085 (2022)",
    doiUrl: "https://doi.org/10.1002/adma.202204085",
  },
  {
    year: 2022,
    image: "Publication/Ultrawide meta-film replication process for the mass production of a flexible microwave absorbing meta-surface.jpg",
    title: "Ultrawide meta-film replication process for the mass production of a flexible microwave absorbing meta-surface",
    authors: "Jun Sae Han*, Hyeonjin Park, Ji-Young Jeong, Joonkyo Jung, Eun-Ji Gwak, Eun-chae Jeon, Tae-Jin Je, Jonghwa Shin, Doo-Sun Choi‡",
    journal: "Optics Express 30, 29760-29771 (2022)",
    doiUrl: "https://doi.org/10.1364/oe.465032",
  },
  {
    year: 2022,
    image: "Publication/Nanoscale physical unclonable function labels based on block copolymer self-assembly.webp",
    title: "Nanoscale physical unclonable function labels based on block copolymer self-assembly",
    authors: "Jang Hwan Kim*, Suwan Jeon, Jae Hyun In, Seonho Nam, Hyeong Min Jin, Kyu Hyo Han, Geon Gug Yang, Hee Jae Choi, Kyung Min Kim, Jonghwa Shin, Seung-Woo Son, Seok Joon Kwon‡, Bong Hoon Kim‡, Sang Ouk Kim‡",
    journal: "Nature Electronics 5, 433-442 (2022)",
    doiUrl: "https://doi.org/10.1038/s41928-022-00788-w",
  },
  {
    year: 2022,
    image: "Publication/Photolithographic realization of target nanostructures in 3D space by inverse design of phase modulation.jpg",
    title: "Photolithographic realization of target nanostructures in 3D space by inverse design of phase modulation",
    authors: "Sang-Hyeon Nam*, Myungjoon Kim*, Nayoung Kim*, Donghwi Cho, Myungwoo Choi, Jun Hyung Park, Jonghwa Shin‡, Seokwoo Jeon‡",
    journal: "Science Advances 8, eabm6310 (2022)",
    doiUrl: "https://doi.org/10.1126/sciadv.abm6310",
  },
  {
    year: 2022,
    image: "Publication/Data-driven concurrent nanostructure optimization based on conditional generative adverserial networks.png",
    title: "Data-driven concurrent nanostructure optimization based on conditional generative adverserial networks",
    authors: "Arthur Baucour*, Myungjoon Kim, Jonghwa Shin‡",
    journal: "Nanophotonics 11, 2865-2873 (2022)",
    doiUrl: "https://doi.org/10.1515/nanoph-2022-0005",
  },
  {
    year: 2022,
    image: "Publication/Machine learning assisted synthesis of lithium-ion batteries cathode materials.jpg",
    title: "Machine learning assisted synthesis of lithium-ion batteries cathode materials",
    authors: "Chi Hao Liow*, Hyeonmuk Kang, Seunggu Kim, Moony Na, Yongju Lee, Arthur Baucour, Kihoon Bang, Yoonsu Shim, Jacob Choe, Gyuseong Hwang, Seongwoo Cho, Gun Park, Jiwon Yeom, Joshua C. Agar, Jong Min Yuk, Jonghwa Shin, Hyuck Mo Lee, Hye Ryung Byon, EunAe Cho, Seungbum Hong‡",
    journal: "Nano Energy 98, 107214 (2022)",
    doiUrl: "https://doi.org/10.1016/j.nanoen.2022.107214",
  },
  {
    year: 2022,
    image: "Publication/All-Color Sub-ambient Radiative Cooling Based on Photoluminescence.gif",
    title: "All-Color Sub-ambient Radiative Cooling Based on Photoluminescence",
    authors: "Seokhwan Min*, Suwan Jeon*, Kyungsun Yun, Jonghwa Shin‡",
    journal: "ACS Photonics 9, 1196-1205 (2022)",
    doiUrl: "https://doi.org/10.1021/acsphotonics.1c01648",
  },
  {
    year: 2022,
    image: "Publication/Photonic topological Lifshitz interfaces.jpg",
    title: "Photonic topological Lifshitz interfaces",
    authors: "Xianji Piao*, Jonghwa Shin, Namkyoo Park‡",
    journal: "Nanophotonics 11, 1211-1217 (2022)",
    doiUrl: "https://doi.org/10.1515/nanoph-2021-0807",
  },
  {
    year: 2021,
    image: "Publication/Ultrawideband electromagnetic metamaterial absorber utilizing coherent absorptions and surface plasmon polaritons based on double layer carbon metapatterns.webp",
    title: "Ultrawideband electromagnetic metamaterial absorber utilizing coherent absorptions and surface plasmon polaritons based on double layer carbon metapatterns",
    authors: "Yongjune Kim*, Pyoungwon Park, Jeongdai Jo, Joonsik Lee, Leekyo Jeong, Jonghwa Shin, Jeong-Hae Lee‡, Hak-Joo Lee‡",
    journal: "Scientific Reports 11, 23045 (2021)",
    doiUrl: "https://doi.org/10.1038/s41598-021-02303-1",
  },
  {
    year: 2021,
    image: "Publication/Colloidal deposition of colored daytime radiative cooling films using nanoparticle-based inks.jpg",
    title: "Colloidal deposition of colored daytime radiative cooling films using nanoparticle-based inks",
    authors: "Tae Yeol Yoon*, Soomin Son*, Seokhwan Min, Dongwoo Chae, Ho Young Woo, Ji-Yeon Chae, Hangyu Lim, Jonghwa Shin, Taejong Paik‡, Heon Lee‡",
    journal: "Materials Today Physics 21, 100510 (2021)",
    doiUrl: "https://doi.org/10.1016/j.mtphys.2021.100510",
  },
  {
    year: 2021,
    image: "Publication/Fabrication and characterization of resistive double square loop arrays for ultra-wide bandwidth microwave absorption.webp",
    title: "Fabrication and characterization of resistive double square loop arrays for ultra-wide bandwidth microwave absorption",
    authors: "Ji-Young Jeon*, Je-Ryung Lee, Hyeonjin Park, Joonkyo Jung, Doo-Sun Choi, Eun-chae Jeon, Jonghwa Shin, Jun Sae Han‡, Tae-Jin Je‡",
    journal: "Scientific Reports 11, 12767 (2021)",
    doiUrl: "https://doi.org/10.1038/s41598-021-91868-y",
  },
  {
    year: 2021,
    image: "Publication/Self-Assembled Nano-Lotus Pod Metasurface for Light Trapping.gif",
    title: "Self-Assembled Nano-Lotus Pod Metasurface for Light Trapping",
    authors: "Nayeun Lee*, Reehyang Kim, Ju Young Kim, Jong Beom Ko, Sang-Hee Ko Park, Sang Ouk Kim, Mark L. Brongersma, Jonghwa Shin‡",
    journal: "ACS Photonics 8, 1616-1622 (2021)",
    doiUrl: "https://doi.org/10.1021/acsphotonics.0c01882",
  },
  {
    year: 2021,
    image: "Publication/Directional radiation for optimal radiative cooling.jpg",
    title: "Directional radiation for optimal radiative cooling",
    authors: "Suwan Jeon*, Jonghwa Shin‡",
    journal: "Optics Express 6, 8376-8386 (2021)",
    doiUrl: "https://doi.org/10.1364/OE.416475",
  },
  {
    year: 2021,
    image: "Publication/Broadband Meta-Absorber with AuNi Core–Shell Nanowires for Solar Vapor Generator.jpg",
    title: "Broadband Meta-Absorber with Au/Ni Core-Shell Nanowires for Solar Vapor Generator",
    authors: "Soomin Son*, Jaemin Park, Sucheol Ju, Daihong Huh, Junho Jun, Kwan Kim, Pil-Hoon Jung, Heon Lee‡, Seokhwan Min, Jonghwa Shin",
    journal: "Advanced Sustainable Systems 5, 2000217 (2021)",
    doiUrl: "https://doi.org/10.1002/adsu.202000217",
  },
  {
    year: 2020,
    image: "Publication/Extreme anti-reflection enhanced magneto-optic Kerr effect microscopy.webp",
    title: "Extreme anti-reflection enhanced magneto-optic Kerr effect microscopy",
    authors: "Dongha Kim*, Young-wan Oh, Jong Uk Kim, Soogil Lee, Arthur Baucour, Jonghwa Shin, Kab-Jin Kim, Byong-Guk Park, Min-Kyo Seo‡",
    journal: "Nature Communications 11, 5937 (2020)",
    doiUrl: "https://doi.org/10.1038/s41467-020-19724-7",
  },
  {
    year: 2020,
    image: "Publication/Laser Synthesis of MOF-Derived Ni@Carbon for High-Performance Pseudocapacitors.gif",
    title: "Laser Synthesis of MOF-Derived Ni@Carbon for High-Performance Pseudocapacitors",
    authors: "Do Van Lam*, Muhammad Sohail, Jae-hyun Kim, Hak Joo Lee, Seong Ok Han, Jonghwa Shin, Duckjong Kim, Hyunuk Kim‡, Seung-Mo Lee‡",
    journal: "ACS Applied Materials & Interfaces 12, 39154-39162 (2020)",
    doiUrl: "https://doi.org/10.1021/acsami.0c10235",
  },
  {
    year: 2020,
    image: "Publication/Ideal spectral emissivity for radiative cooling of earthbound objects.webp",
    title: "Ideal spectral emissivity for radiative cooling of earthbound objects",
    authors: "Suwan Jeon*, Jonghwa Shin‡",
    journal: "Scientific Reports 10, 13038 (2020)",
    doiUrl: "https://doi.org/10.1038/s41598-020-70105-y",
  },
  {
    year: 2020,
    image: "Publication/Spectrally sharp metasurfaces for wide-angle high extinction of green lasers.jpg",
    title: "Spectrally sharp metasurfaces for wide-angle high extinction of green lasers",
    authors: "Nayoung Kim*, Taeyong Chang, Myungjoon Kim, Minsung Heo, Arthur Baucour, Joonkyo Jung, Jonghwa Shin‡",
    journal: "Optics Express 28, 22121-22134 (2020) [Highlighted as editor's pick]",
    doiUrl: "https://doi.org/10.1364/oe.398255",
  },
  {
    year: 2020,
    image: "Publication/Broadband metamaterials and metasurfaces a review from the perspectives of materials and devices.png",
    title: "Broadband metamaterials and metasurfaces: a review from the perspectives of materials and devices",
    authors: "Joonkyo Jung*, HyeonJin Park*, Junhyung Park*, Taeyong Chang‡, Jonghwa Shin‡",
    journal: "Nanophotonics (2020) [Invited review]",
    doiUrl: "https://doi.org/10.1515/nanoph-2020-0111",
  },
  {
    year: 2020,
    image: "Publication/Mimicking bio-mechanical principles in photonic metamaterials for giant broadband nonlinearity.webp",
    title: "Mimicking bio-mechanical principles in photonic metamaterials for giant broadband nonlinearity",
    authors: "Taeyong Chang*, Suwan Jeon, Minsung Heo, Jonghwa Shin‡",
    journal: "Communications Physics 3, 1-9 (2020) [media coverage]",
    doiUrl: "https://doi.org/10.1038/s42005-020-0352-0",
  },
  {
    year: 2020,
    image: "Publication/High-Contrast Optical Modulation from Strain-Induced Nanogaps at Three-Dimensional Heterogeneous Interfaces.jpg",
    title: "High-Contrast Optical Modulation from Strain-Induced Nanogaps at Three-Dimensional Heterogeneous Interfaces",
    authors: "Donghwi Cho*, Young-Seok Shim, Jae-Wook Jung, Sang-Hyeon Nam, Seokhwan Min, Sang-Eon Lee, Youngjin Ham, Kwangjae Lee, Junyong Park, Jonghwa Shin, Jung-Wuk Hong‡, Seokwoo Jeon‡",
    journal: "Advanced Science 7, 1903708/1-1903708/9 (2020)",
    doiUrl: "https://doi.org/10.1002/advs.201903708",
  },
  {
    year: 2019,
    image: "Publication/Mie resonator method for reliable permittivity measurement of loss-less ceramics in microwave frequency at high temperature.jpeg",
    title: "Mie resonator method for reliable permittivity measurement of loss-less ceramics in microwave frequency at high temperature",
    authors: "Ho Jin Ma*, Joonkyo Jung*, Jung Hoon Kong, Jin Woo Park, Seung Jun Lee, Jonghwa Shin‡, Do Kyung Kim‡",
    journal: "Journal of Applied Physics 126, 094101/1-094101/6 (2019)",
    doiUrl: "https://doi.org/10.1063/1.5093394",
  },
  {
    year: 2019,
    image: "Publication/Photo-stimulated charge transfer in contact electrification coupled with plasmonic excitations.jpg",
    title: "Photo-stimulated charge transfer in contact electrification coupled with plasmonic excitations",
    authors: "Gi Hyeon Han*, Jin Pyo Lee, Hee Jun Kim, Jonghwa Shin, Jeong Min Baik‡",
    journal: "Nano Energy 65, 104031/1-104031/8 (2019)",
    doiUrl: "https://doi.org/10.1016/j.nanoen.2019.104031",
  },
  {
    year: 2019,
    image: "Publication/A General Recipe for Nondispersive Optical Activity in Bilayer Chiral Metamaterials.png",
    title: "A General Recipe for Nondispersive Optical Activity in Bilayer Chiral Metamaterials",
    authors: "Hyun Sung Park*, Jaehyeon Son, Yushin Kim, Hyukjoon Cho, Jonghwa Shin, Wonju Jeon, Bumki Min‡",
    journal: "Advanced Optical Materials 7, 1801729/1-1801729/10 (2019)",
    doiUrl: "https://doi.org/10.1002/adom.201801729",
  },
  {
    year: 2019,
    image: "Publication/Near-atomically flat, chemically homogeneous, electrically conductive optical metasurface.png",
    title: "Near-atomically flat, chemically homogeneous, electrically conductive optical metasurface",
    authors: "Jong Uk Kim*, Suwan Jeon, Minsung Heo, Hwi-Min Kim, Reehyang Kim, Nayoung Kim, Yong-Hee Lee, Jonghwa Shin‡",
    journal: "Nanoscale 11, 9580-9586 (2019)",
    doiUrl: "https://doi.org/10.1039/c8nr10436k",
  },
  {
    year: 2019,
    image: "Publication/Effect of the dielectric constant of a liquid electrolyte on lithium metal anodes.jpg",
    title: "Effect of the dielectric constant of a liquid electrolyte on lithium metal anodes",
    authors: "Ju Young Kim*‡, Dong Ok Shin, Taeyong Chang, Kwang Man Kim, Jiseon Jeong, Joonam Park, Yong Min Lee, Kuk Young Cho, Charudatta Phatak, Seungbum Hong, Young-Gi Lee‡",
    journal: "Electrochimica Acta 300, 299-305 (2019)",
    doiUrl: "https://doi.org/10.1016/j.electacta.2019.01.113",
  },
  {
    year: 2018,
    image: "Publication/Ultralarge Area Sub-10nm Plasmonic Nanogap Array by Block Copolymer Self-Assembly for Reliable High-Sensitivity SERS.gif",
    title: "Ultralarge Area Sub-10nm Plasmonic Nanogap Array by Block Copolymer Self-Assembly for Reliable High-Sensitivity SERS",
    authors: "Hyeong Min Jin*, Ju Young Kim*, Minsung Heo, Seong-Jun Jeong, Bong Hoon Kim, Seung Keun Cha, Kyu Hyo Han, Jang Hwan Kim, Geon Gug Yang, Jonghwa Shin‡, Sang Ouk Kim‡",
    journal: "ACS Applied Materials & Interfaces 10, 44660-44667 (2018)",
    doiUrl: "https://doi.org/10.1021/acsami.8b17325",
  },
  {
    year: 2018,
    image: "Publication/Pyramidal Metal-dielectric hybrid-structure geometry with an asymmetric TiO2 layer for broadband light absorption and photocatalytic applications.jpg",
    title: "Pyramidal Metal-dielectric hybrid-structure geometry with an asymmetric TiO2 layer for broadband light absorption and photocatalytic applications",
    authors: "Hee Jun Kim*, Junho Jun, Hak-Jong Choi, Hyunah Kwon, Junha Park, Changwon Seo, Jong Kyu Kim, Jonghwa Shin, Jeongyong Kim, Heon Lee‡, and Jeong Min Baik‡",
    journal: "Nano Energy 53, 468-474 (2018)",
    doiUrl: "https://doi.org/10.1016/j.nanoen.2018.08.074",
  },
  {
    year: 2018,
    image: "Publication/Bright and vivid plasmonic color filters having dual resonance modes with proper orthogonality.jpg",
    title: "Bright and vivid plasmonic color filters having dual resonance modes with proper orthogonality",
    authors: "Hyowook Kim*, Myungjoon Kim, Taeyong Chang, Arthur Baucour, Suwan Jeon, Nayoung Kim, Hak-Jong Choi, Heon Lee, and Jonghwa Shin‡",
    journal: "Optics Express 26, 27403-27417 (2018)",
    doiUrl: "https://doi.org/10.1364/oe.26.027403",
  },
  {
    year: 2018,
    image: "Publication/Direct Chemical Synthesis of Plasmonic Black Colloidal Gold Superparticles with Broadband Absorption Properties.gif",
    title: "Direct Chemical Synthesis of Plasmonic Black Colloidal Gold Superparticles with Broadband Absorption Properties",
    authors: "Nayoung Kwon*, Hwisu Oh, Reehyang Kim, Arjyabaran Sinha, Jaeyun Kim, Jonghwa Shin, James W. M. Chon‡, and Byungkwon Lim‡",
    journal: "Nano Letters 18, 5927-5932 (2018)",
    doiUrl: "https://doi.org/10.1021/acs.nanolett.8b02629",
  },
  {
    year: 2018,
    image: "Publication/Finite-difference time-domain analysis of increased penetration depth in optical coherence tomography by wavefront shaping.jpg",
    title: "Finite-difference time-domain analysis of increased penetration depth in optical coherence tomography by wavefront shaping",
    authors: "Jong Uk Kim*, Hyun Choi, YongKeun Park, and Jonghwa Shin‡",
    journal: "Biomedical Optics Express 9, 3883-3897 (2018)",
    doiUrl: "https://doi.org/10.1364/boe.9.003883",
  },
  {
    year: 2018,
    image: "Publication/Metal Nanoparticle Array as a Tunable Refractive Index Material over Broad Visible and Infrared Wavelengths.gif",
    title: "Metal Nanoparticle Array as a Tunable Refractive Index Material over Broad Visible and Infrared Wavelengths",
    authors: "Reehyang Kim*, Kyungjae Chung, Ju Young Kim, Yunyong Nam, Sang-Hee Ko Park, and Jonghwa Shin‡",
    journal: "ACS Photonics 7, 1188-1195 (2018)",
    doiUrl: "https://doi.org/10.1021/acsphotonics.7b01497",
  },
  {
    year: 2018,
    image: "Publication/Transferrable Plasmonic Au Thin Film Containing Sub-20 nm Nanohole Array Constructed via High-Resolution Polymer Self-Assembly and Nanotransfer Printing.gif",
    title: "Transferrable Plasmonic Au Thin Film Containing Sub-20 nm Nanohole Array Constructed via High-Resolution Polymer Self-Assembly and Nanotransfer Printing",
    authors: "Soonmin Yim*, Suwan Jeon, Jong Min Kim, Kwang Min Baek, Gun Ho Lee, Hyowook Kim, Jonghwa Shin, and Yeon Sik Jung‡",
    journal: "ACS Applied Materials & Interfaces 10, 2216-2223 (2018)",
    doiUrl: "https://doi.org/10.1021/acsami.7b16401",
  },
  {
    year: 2018,
    image: "Publication/Bimodal phase separated block copolymer homopolymer blends self-assembly for hierarchical porous metal nanomesh electrodes.png",
    title: "Bimodal phase separated block copolymer/homopolymer blends self-assembly for hierarchical porous metal nanomesh electrodes",
    authors: "Ju Young Kim*, Hyeong Min Jin*, Seong-Jun Jeong, Taeyong Chang, Bong Hoon Kim, Seung Keun Cha, Jun Soo Kim, Dong Ok Shin, Jin Young Choi, Jang Hwan Kim, Geon Gug Yang, Suwan Jeon, Young-Gi Lee, Kwang Man Kim, Jonghwa Shin‡ and Sang Ouk Kim‡",
    journal: "Nanoscale 10, 100-108 (2018)",
    doiUrl: "https://doi.org/10.1039/c7nr07178g",
  },
  {
    year: 2017,
    image: "Publication/Signal self-enhancement by coordinated assembly of gold nanoparticles enables accurate one-step-immunoassays.png",
    title: "Signal self-enhancement by coordinated assembly of gold nanoparticles enables accurate one-step-immunoassays",
    authors: "J-H. Kwon*, H-T. Kim, J-H. Lee, R. Kim, M. Heo, J. Shin, H-Y. Lee, Y. J. Cha, and J. Lee‡",
    journal: "Nanoscale 9, 16476-16484 (2017)",
    doiUrl: "https://doi.org/10.1039/c7nr03453a",
  },
  {
    year: 2016,
    image: "Publication/Highly tunable refractive index visible-light metasurface from block copolymer self-assembly.webp",
    title: "Highly tunable refractive index visible-light metasurface from block copolymer self-assembly",
    authors: "Ju Young Kim*, Hyowook Kim, Bong Hoon Kim, Taeyong Chang, Joonwon Lim, Hyeong Min Jin, Jeong Ho Mun, Young Joo Choi, Kyungjae Chung, Shanhui Fan, Jonghwa Shin‡ and Sang Ouk Kim‡",
    journal: "Nature Communications 7, 12911 (2016)",
    doiUrl: "https://doi.org/10.1038/ncomms12911",
  },
  {
    year: 2016,
    image: "Publication/Broadband giant-refractive-index material based on mesoscopic space-filling curves.webp",
    title: "Broadband giant-refractive-index material based on mesoscopic space-filling curves",
    authors: "Taeyong Chang*, Jong Uk Kim, Seung Kyu Kang, Hyowook Kim, Do Kyung Kim, Yong-Hee Lee and Jonghwa Shin‡",
    journal: "Nature Communications 7, 12661 (2016)",
    doiUrl: "https://doi.org/10.1038/ncomms12661",
  },
  {
    year: 2016,
    image: "Publication/Complex High Aspect Ratio Metal Nanostructures by Secondary Sputtering Phenomenon Combined with Block Copolymer Self-Assembly.png",
    title: "Complex High Aspect Ratio Metal Nanostructures by Secondary Sputtering Phenomenon Combined with Block Copolymer Self-Assembly",
    authors: "Hwan-Jin Jeon*‡, Ju Young Kim*, Woo-Bin Jung*, Hyeon-Su Jeong, Yun Ho Kim, Dong Ok Shin, Jonghwa Shin‡, Sang Ouk Kim‡ and Hee-Tae Jung‡",
    journal: "Advanced Materials 28, 8439-8445 (2016)",
    doiUrl: "https://doi.org/10.1002/adma.201602523",
  },
  {
    year: 2016,
    image: "Publication/Optical effective media with independent control of permittivity and permeability based on conductive particles.jpeg",
    title: "Optical effective media with independent control of permittivity and permeability based on conductive particles",
    authors: "Kyungjae Chung*, Reehyang Kim*, Taeyong Chang and Jonghwa Shin‡",
    journal: "Applied Physics Letters 109, 021114 (2016)",
    doiUrl: "https://doi.org/10.1063/1.4958987",
  },
  {
    year: 2016,
    image: "Publication/Fabrication of 50 nm scale Pt nanostructures by block copolymer (BCP) and its characteristics of surface-enhanced Raman scattering (SERS).png",
    title: "Fabrication of 50 nm scale Pt nanostructures by block copolymer (BCP) and its characteristics of surface-enhanced Raman scattering (SERS)",
    authors: "Jae Hee Shin*, Hyun Gu Kim, Gwang Min Baek, Reehyang Kim, Suwan Jeon, Jeong Ho Mun, Han-Bo-Ram Lee, Yeon Sik Jung, Sang Ouk Kim, Kyoung Nam Kim and Geun Young Yeom‡",
    journal: "RSC Advances 6, 70756-70762 (2016)",
    doiUrl: "https://doi.org/10.1039/c6ra08608j",
  },
  {
    year: 2016,
    image: "Publication/Flexible Near-Field Nanopatterning with Ultrathin, Conformal Phase Masks on Nonplanar Substrates for Biomimetic Hierarchical Photonic Structures.gif",
    title: "Flexible Near-Field Nanopatterning with Ultrathin, Conformal Phase Masks on Nonplanar Substrates for Biomimetic Hierarchical Photonic Structures",
    authors: "Young Woo Kwon*, Junyong Park*, Taehoon Kim, Seok Hee Kang, Hyowook Kim, Jonghwa Shin, Seokwoo Jeon‡ and Suck Won Hong‡",
    journal: "ACS Nano 10, 4609-4617 (2016)",
    doiUrl: "https://doi.org/10.1021/acsnano.6b00816",
  },
  {
    year: 2016,
    image: "Publication/Two-dimensional metal-dielectric hybrid-structured film with titanium oxide for enhanced visible light absorption and photo-catalytic application.jpg",
    title: "Two-dimensional metal-dielectric hybrid-structured film with titanium oxide for enhanced visible light absorption and photo-catalytic application",
    authors: "Joonmo Park*, Hee Jun Kim, SangHyeon Nam, Hyowook Kim, Hak-Jong Choi, Youn Jeong Jang, JaeSung Lee, Jonghwa Shin, Heon Lee‡ and Jeong Min Baik‡",
    journal: "Nano Energy 21, 115-122 (2016)",
    doiUrl: "https://doi.org/10.1016/j.nanoen.2016.01.004",
  },
  {
    year: 2016,
    image: "Publication/Synergistic Concurrent Enhancement of Charge Generation, Dissociation, and Transport in Organic Solar Cells with Plasmonic Metal-Carbon Nanotube Hybrids.png",
    title: "Synergistic Concurrent Enhancement of Charge Generation, Dissociation, and Transport in Organic Solar Cells with Plasmonic Metal-Carbon Nanotube Hybrids",
    authors: "Ju Min Lee*, Joonwon Lim, Nayeun Lee, Hyung Il Park, Kyung Eun Lee, Taewoo Jeon, Soo Ah Nam, Jehan Kim, Jonghwa Shin, and Sang Ouk Kim‡",
    journal: "Advanced Materials 27, 1519-1525 (2016)",
    doiUrl: "https://doi.org/10.1002/adma.201404248",
  },
  {
    year: 2015,
    image: "Publication/One-way optical modal transition based on causality in momentum space.jpg",
    title: "One-way optical modal transition based on causality in momentum space",
    authors: "Sunkyu Yu*, Xianji Piao, KyungWan Yoo, Jonghwa Shin and Namkyoo Park‡",
    journal: "Optics Express 23, 24997-25008 (2015)",
    doiUrl: "https://doi.org/10.1364/oe.23.024997",
  },
  {
    year: 2015,
    image: "Publication/Aluminum Nanoarrays for Plasmon-Enhanced Light Harvesting.gif",
    title: "Aluminum Nanoarrays for Plasmon-Enhanced Light Harvesting",
    authors: "Minah Lee*, Jong Uk Kim, Ki Joong Lee, Soohoon Ahn, Jonghwa Shin‡ and Chan Beum Park‡",
    journal: "ACS Nano 9, 6206-6213 (2015)",
    doiUrl: "https://doi.org/10.1021/acsnano.5b01541",
  },
  {
    year: 2015,
    image: "Publication/Au–Ag Core–Shell Nanoparticle Array by Block Copolymer Lithography for Synergistic Broadband Plasmonic Properties.gif",
    title: "Au–Ag Core–Shell Nanoparticle Array by Block Copolymer Lithography for Synergistic Broadband Plasmonic Properties",
    authors: "Seung Keun Cha*, Jeong Ho Mun, Taeyong Chang, Sang Yun Kim, Ju Young Kim, Hyeong Min Jin, Jeong Yong Lee, Jonghwa Shin, Kwang Ho Kim‡, and Sang Ouk Kim‡",
    journal: "ACS Nano 9, 5536-5543 (2015)",
    doiUrl: "https://doi.org/10.1021/acsnano.5b01641",
  },
  {
    year: 2015,
    image: "Publication/Fast and bright spontaneous emission of Er3+ ions in metallic nano-cavity.webp",
    title: "Fast and bright spontaneous emission of Er3+ ions in metallic nano-cavity",
    authors: "Jung-Hwan Song*, Jisu Kim*, Hoon Jang, In Yong Kim, Indra Karnadi, Jonghwa Shin, Jung H. Shin and, Yong-Hee Lee‡",
    journal: "Nature Communications 6, 7080 (2015)",
    doiUrl: "https://doi.org/10.1038/ncomms8080",
  },
  {
    year: 2015,
    image: "Publication/Self-aligned deterministic coupling of single quantum emitter to nanofocused plasmonic modes.jpeg",
    title: "Self-aligned deterministic coupling of single quantum emitter to nanofocused plasmonic modes",
    authors: "Su-Hyun Gong*, Je-Hyung Kim, Young-Ho Ko, Christoph Rodriguez, Jonghwa Shin, Yong-Hee Lee, Le Si Dangd, Xiang Zhang, and Yong-Hoon Cho‡",
    journal: "Proceedings of the National Academy of Sciences 112, 5280-5285 (2015)",
    doiUrl: "https://doi.org/10.1073/pnas.1418049112",
  },
  {
    year: 2015,
    image: "Publication/Anomalous Rapid Defect Annihilation in Self-Assembled Nanopatterns by Defect Melting.gif",
    title: "Anomalous Rapid Defect Annihilation in Self-Assembled Nanopatterns by Defect Melting",
    authors: "Bong Hoon Kim*, So Jung Park, Hyeong Min Jin, Ju Young Kim, Seung-Woo Son, Myung-Hyun Kim, Chong Min Koo, Jonghwa Shin, Jaeup U. Kim, and Sang Ouk Kim‡",
    journal: "Nano Letters 15, 1190-1196 (2015)",
    doiUrl: "https://doi.org/10.1021/nl5042935",
  },
  {
    year: 2014,
    image: "Publication/Negative-Tone Block Copolymer Lithography by In Situ Surface Chemical Modification.png",
    title: "Negative-Tone Block Copolymer Lithography by In Situ Surface Chemical Modification",
    authors: "Bong Hoon Kim*, Kyeong-Jae Byeon, Ju Young Kim, Jinseung Kim, Hyeong Min Jin, Joong-Yeon Cho, Seong-Jun Jeong, Jonghwa Shin, Heon Lee‡, and Sang Ouk Kim‡",
    journal: "Small 10, 4207-4212 (2014)",
    doiUrl: "https://doi.org/10.1002/smll.201400971",
  },
  {
    year: 2014,
    image: "Publication/Nanodomain Swelling Block Copolymer Lithography for Morphology Tunable Metal Nanopatterning.png",
    title: "Nanodomain Swelling Block Copolymer Lithography for Morphology Tunable Metal Nanopatterning",
    authors: "Jeong Ho Mun*, Seung Keun Cha, Hyowook Kim, Hyoung-Seok Moon, Ju Young Kim, Hyeong Min Jin, Young joo Choi, Jeong Eun Beak, Jonghwa Shin‡ and, Sang Ouk Kim‡",
    journal: "Small 10, 3742-3749 (2014)",
    doiUrl: "https://doi.org/10.1002/smll.201400600",
  },
  {
    year: 2014,
    image: "Publication/Full-Field Subwavelength Imaging Using a Scattering Superlens.png",
    title: "Full-Field Subwavelength Imaging Using a Scattering Superlens",
    authors: "Chunghyun Park*, Jung-Hoon Park, Christophe Rodrigues, HyeonSeung Yu, Minkwan Kim, Kyoungsuk Jin, Seungyong Han, Jonghwa Shin, Seung Hwan Ko, Ki Tae Nam, Yong-Hee Lee, Yong-Hoon Cho‡ and YongKeun Park‡",
    journal: "Physical Review Letters 113, 113901 (2014)",
    doiUrl: "https://doi.org/10.1103/PhysRevLett.113.113901",
  },
  {
    year: 2014,
    image: "Publication/Mussel-Inspired Plasmonic Nanohybrids for Light Harvesting.jpg",
    title: "Mussel-Inspired Plasmonic Nanohybrids for Light Harvesting",
    authors: "Minah Lee*, Jong Uk Kim, Joon Seok Lee, Byung Il Lee, Jonghwa Shin‡ and Chan Beum Park‡",
    journal: "Advanced Materials 26, 4463-4468 (2014)",
    doiUrl: "https://doi.org/10.1002/adma.201305766",
  },
  {
    year: 2014,
    image: "Publication/Optical vortex arrays from smectic liquid crystals.jpg",
    title: "Optical vortex arrays from smectic liquid crystals",
    authors: "Baeksik Son*, Sejeong Kim*, Yun Ho Kim K. Kalantar, Hwi-Min Kim, Hyeon-Su Jeong, Siyoung Q. Choi, Jonghwa Shin, Hee-Tae Jung and Yong-Hee Lee‡",
    journal: "Optics Express 22, 4699-4704 (2014)",
    doiUrl: "https://doi.org/10.1364/OE.22.004699",
  },
  {
    year: 2013,
    image: "Publication/Multicomponent nanopatterns by directed block copolymer self-assembly.gif",
    title: "Multicomponent nanopatterns by directed block copolymer self-assembly",
    authors: "D.-O. Shin*, J.-H. Mun*, G.-T. Hwang, J.-M. Yoon, J.-Y. Kim, J.-M. Yun, Y.-B. Yang, Y. Oh, J.-Y. Lee, J. Shin, K.-J. Lee, S. Park, J.-U. Kim, S.-O. Kim‡",
    journal: "ACS Nano 10, 8899 (2013)",
    doiUrl: "https://doi.org/10.1021/nn403379k",
  },
  {
    year: 2013,
    image: "Publication/Subwavelength light focusing using random nanoparticles.webp",
    title: "Subwavelength light focusing using random nanoparticles",
    authors: "J.-H. Park*, C. Park, H.-S. Yu, J. Park, S. Han, J. Shin, S. H. Ko, K. T. Nam, Y.-H. Cho‡, and Y. Park‡",
    journal: "Nature Photonics 7, 454 (2013)",
    doiUrl: "https://doi.org/10.1038/nphoton.2013.95",
  },
  {
    year: 2012,
    image: "Publication/Metallic nanocavity enhanced second harmonic generation from a KNbO3 nonlinear nanowire.jpg",
    title: "Metallic nanocavity enhanced second harmonic generation from a KNbO3 nonlinear nanowire",
    authors: "S.-Y. Kang*, J. Shin‡, K.-Y. Jeong, C.-M. Lee, K.-J. Yee, and Y.-H. Lee",
    journal: "Photonics and Nanostructures - Fundamentals and Applications 10, 534 (2012)",
    doiUrl: "https://doi.org/10.1016/j.photonics.2012.04.006",
  },
  {
    year: 2011,
    image: "Publication/Optical recoil of asymmetric nano-optical antenna.jpg",
    title: "Optical recoil of asymmetric nano-optical antenna",
    authors: "J.-H. Song*, J. Shin‡, H.-J. Lim, and Y.-H. Lee",
    journal: "Optics Express 19, 14929 (2011)",
    doiUrl: "https://doi.org/10.1364/OE.19.014929",
  },
  {
    year: 2011,
    image: "Publication/Deterministic nanotexturing by directional photofluidization lithography.jpg",
    title: "Deterministic nanotexturing by directional photofluidization lithography",
    authors: "S. Lee*, J. Shin, H. S. Kang, Y.-H. Lee, and J.-K. Park‡",
    journal: "Advanced Materials 23, 3244 (2011)",
    doiUrl: "https://doi.org/10.1002/adma.201100662",
  },
  {
    year: 2011,
    image: "Publication/Frequency selective heterojunction metalinsulator-metal mirror for surface plasmons.png",
    title: "Frequency selective heterojunction metalinsulator-metal mirror for surface plasmons",
    authors: "Y. Hwang*, J. Shin, J-E. Kim, H. Y. Park, and C.-S. Kee‡",
    journal: "Physical Review B 83, 235131 (2011)",
    doiUrl: "https://doi.org/10.1103/PhysRevB.83.235131",
  },
  {
    year: 2011,
    image: "Publication/A terahertz metamaterial with unnaturally high refractive index.webp",
    title: "A terahertz metamaterial with unnaturally high refractive index",
    authors: "M. Choi*, S. H. Lee*, Y. Kim, S. B. Kang, J. Shin, M. H. Kwak, K.-Y. Kang, Y.-H. Lee, N. Park, and B. Min‡",
    journal: "Nature 470, 369 (2011)",
    doiUrl: "https://doi.org/10.1038/nature09776",
  },
  {
    year: 2010,
    image: "Publication/Fabrication of the funnel-shaped three-dimensional plasmonic tip arrays by directional photofluidization lithography.gif",
    title: "Fabrication of the funnel-shaped three-dimensional plasmonic tip arrays by directional photofluidization lithography",
    authors: "S. Lee*, J. Shin, Y.-H. Lee, and J.-K. Park‡",
    journal: "ACS Nano 4, 7175 (2010)",
    doiUrl: "https://doi.org/10.1021/nn1017507",
  },
  {
    year: 2010,
    image: "Publication/Transmission through a scalar wave three-dimensional electromagnetic metamaterial and the implication for polarization control.jpg",
    title: "Transmission through a scalar wave three-dimensional electromagnetic metamaterial and the implication for polarization control",
    authors: "J. Shin*, J.-T. Shen, and S. Fan‡",
    journal: "Journal of Nanoscience and Nanotechnology 10, 1737 (2010) (invited)",
    doiUrl: "https://doi.org/10.1166/jnn.2010.2036",
  },
  {
    year: 2010,
    image: "Publication/One-dimensional metal nanowire assembly via block copolymer soft graphoepitaxy.gif",
    title: "One-dimensional metal nanowire assembly via block copolymer soft graphoepitaxy",
    authors: "S.-J. Jeong*, H.-S. Moon, J. Shin, B. H. Kim, D. O. Shin, J. Y. Kim, Y.-H. Lee, J. U. Kim‡, and S. O. Kim‡",
    journal: "Nano Letters 10, 3500 (2010)",
    doiUrl: "https://doi.org/10.1021/nl101637f",
  },
  {
    year: 2010,
    image: "Publication/Directional photofluidization lithography for nanoarchitectures with controlled shapes and sizes.gif",
    title: "Directional photofluidization lithography for nanoarchitectures with controlled shapes and sizes",
    authors: "S. Lee*, J. Shin, Y.-H. Lee, S. Fan, and J.-K. Park‡",
    journal: "Nano Letters 10, 296 (2010)",
    doiUrl: "https://doi.org/10.1021/nl903570c",
  },
  {
    year: 2009,
    image: "Publication/Extraordinary magnetic field enhancement with metallic nanowire role of surface impedance in Babinet_s principle for sub-skin-depth regime.png",
    title: "Extraordinary magnetic field enhancement with metallic nanowire: role of surface impedance in Babinet's principle for sub-skin-depth regime",
    authors: "S. Koo*, S. Kumar, J. Shin, D. Kim, and N. Park‡",
    journal: "Physical Review Letters 103, 263901 (2009)",
    doiUrl: "https://doi.org/10.1103/physrevlett.103.263901",
  },
  {
    year: 2009,
    image: "Publication/Three-dimensional metamaterials with an ultra-high effective refractive index over broad bandwidth.png",
    title: "Three-dimensional metamaterials with an ultra-high effective refractive index over broad bandwidth",
    authors: "J. Shin*, J.-T. Shen, and S. Fan‡",
    journal: "Physical Review Letters 102, 093903 (2009)",
    doiUrl: "https://doi.org/10.1103/physrevlett.102.093903",
  },
  {
    year: 2009,
    image: "Publication/Two-dimensionally relocatable microfiber-coupled photonic crystal resonator.jpg",
    title: "Two-dimensionally relocatable microfiber-coupled photonic crystal resonator",
    authors: "J.-Y. Kim*, M.-K. Kim, M.-K. Seo, S.-H. Kwon, J. Shin, and Y.-H. Lee‡",
    journal: "Optics Express 17, 13009 (2009)",
    doiUrl: "https://doi.org/10.1364/oe.17.013009",
  },
  {
    year: 2007,
    image: "Publication/Three-dimensional electromagnetic metamaterials that homogenize to uniform non-Maxwellian media.jpg",
    title: "Three-dimensional electromagnetic metamaterials that homogenize to uniform non-Maxwellian media",
    authors: "J. Shin*, J.-T. Shen, and S. Fan‡",
    journal: "Physical Review B 76, 113101 (2007)",
    doiUrl: "https://doi.org/10.1103/physrevb.76.113101",
  },
  {
    year: 2006,
    image: "Publication/Cut-through metal slit array as an anisotropic metamaterial film.gif",
    title: "Cut-through metal slit array as an anisotropic metamaterial film",
    authors: "J. Shin*, J.-T. Shen, P. B. Catrysse, and S. Fan‡",
    journal: "IEEE Journal of Selected Topics in Quantum Electronics 12, 1116 (2006) (invited)",
    doiUrl: "https://doi.org/10.1109/jstqe.2006.879577",
  },
  {
    year: 2006,
    image: "Publication/Conditions for designing single-mode air-core waveguides in threedimensional photonic crystals.jpeg",
    title: "Conditions for designing single-mode air-core waveguides in threedimensional photonic crystals",
    authors: "V. Lousse*, J. Shin, and S. Fan‡",
    journal: "Applied Physics Letters 89, 161103 (2006)",
    doiUrl: "https://doi.org/10.1063/1.2362983",
  },
  {
    year: 2005,
    image: "Publication/Conditions for self-collimation in three-dimensional photonic crystals.jpg",
    title: "Conditions for self-collimation in three-dimensional photonic crystals",
    authors: "J. Shin* and S. Fan‡",
    journal: "Optics Letters 30, 2397 (2005)",
    doiUrl: "https://doi.org/10.1364/ol.30.002397",
  },
  {
    year: 2004,
    image: "Publication/Simulations of the effect of the core ring on surface and air-core modes in photonic band gap fibers.jpg",
    title: "Simulations of the effect of the core ring on surface and air-core modes in photonic band gap fibers",
    authors: "H. K. Kim*, M. Digonnet, G. Kino, J. Shin, and S. Fan‡",
    journal: "Optics Express 12, 3436 (2004)",
    doiUrl: "https://doi.org/10.1364/opex.12.003436",
  },
  {
    year: 2004,
    image: "Publication/Designing air-core photonic-bandgap fibers free of surface modes.gif",
    title: "Designing air-core photonic band gap fibers free of surface modes",
    authors: "H. K. Kim*, J. Shin, S. Fan, M. J. F. Digonnet, and G. S. Kino‡",
    journal: "IEEE Journal of Quantum Electronics 40, 551 (2004)",
    doiUrl: "https://doi.org/10.1109/jqe.2004.826429",
  },
  {
    year: 2004,
    image: "Publication/Simple geometric criterion to predict the existence of surface modes in air-core photonic band gap fibers.jpg",
    title: "Simple geometric criterion to predict the existence of surface modes in air-core photonic band gap fibers",
    authors: "M. Digonnet*, H. Kim, J. Shin, S. Fan, and G. Kino‡",
    journal: "Optics Express 12, 1864 (2004)",
    doiUrl: "https://doi.org/10.1364/opex.12.001864",
  },
];
